### ISSUE TITLE
can't complie the SEAL

### ISSUE THREAD

**Issue by zhifeng110** [alibaba-edu/mpc4j#3] opened 2022-09-22 02:41 UTC
Hi, I created a ubuntu: 20.04 container in Docker. 
I encountered this problem when executing "make". What can I do to solve it？

![图片](https://user-images.githubusercontent.com/38159898/191646324-7d79650a-9755-48be-9bd5-f53105bef41f.png)
![图片](https://user-images.githubusercontent.com/38159898/191646334-b4323dcf-b428-4b59-9802-e24bd7a21266.png)

**Comment by liuweiran900217** [comment] 2022-09-22 02:46
Does the error occurs when compiling SEAL instead of mpc4j-native-fhe? Can you successfully install SEAL using apt-get install?

**Comment by liuweiran900217** [comment] 2022-09-22 02:48
As far as I understand, the error is related to libz.a. Can you try installing libz following the step shown in https://zoomadmin.com/HowToInstall/UbuntuPackage/libz-dev?

**Comment by iF2007** [comment] 2022-09-22 02:55
I believe this issue is not related to mpc4j. This should be a SEAL-related issue. One possible direction is to check libz-related problems.

**Comment by iF2007** [comment] 2022-09-22 03:02
[DataTrust](https://dp.alibaba.com/product/datatrust) also uses SEAL-related modules of mpc4j, e.g. FHE-based asymmetric PSI, running in container environment. Therefore it is possible to build and run mpc4j in a container.

**Comment by iF2007** [comment] 2022-09-22 03:13
One possible solution is to download [libz](https://www.zlib.net/), then compile and install locally.

**Comment by shazi4399** [comment] 2022-10-06 01:14
I'm with similar error (maybe complaining x64 libz.a not compatible),but I haven't solved it yet.

**Comment by liuweiran900217** [comment] 2022-10-08 01:39
> I'm with similar error (maybe complaining x64 libz.a not compatible),but I haven't solved it yet. ![image](https://user-images.githubusercontent.com/25169930/194192236-9cfd2c9a-ab9c-4bdd-a38e-d82c7cb4297a.png)

It seems there are some linked libraries related to SEAL. If you1 have any problems installing SEAL based on the source code, we highly recommand using the command "apt-get install seal" to automatically install SEAL and related libraries. Please let me know if "apt-get install seal" works well.

**Comment by shazi4399** [comment] 2022-10-10 02:38
> > I'm with similar error (maybe complaining x64 libz.a not compatible),but I haven't solved it yet. ![image](https://user-images.githubusercontent.com/25169930/194192236-9cfd2c9a-ab9c-4bdd-a38e-d82c7cb4297a.png)
> 
> It seems there are some linked libraries related to SEAL. If you1 have any problems installing SEAL based on the source code, we highly recommand using the command "apt-get install seal" to automatically install SEAL and related libraries. Please let me know if "apt-get install seal" works well.

I followed the guide to install seal on a new computer（Ubuntu18.04） and still get the same error.
![image](https://user-images.githubusercontent.com/25169930/194791700-b8fdc22d-73c8-4645-89c0-981f5f653627.png)

Then, I tried to install seal again as your suggested command `sudo apt-get install SEAL` or `sudo apt-get install seal`.But it shows that the installation package cannot be found.
![image](https://user-images.githubusercontent.com/25169930/194792154-ffe991a7-3432-422a-ba78-f902fbbb2ebe.png)

And, I tried to search for the existence of the SEAL installation package, but nothing was found
![image](https://user-images.githubusercontent.com/25169930/194792240-9f9f12d6-57a8-47be-9313-788a7981fa23.png)

**Comment by liuweiran900217** [comment] 2022-10-10 03:20
I am sorry for providing a wrong way of installing. It seems there are some problems when installing SEAL in Docker. Currently I cannot figure out why the problem occurs. Can you try installing SEAL without using Docker? 

Besides, I think the problem is related to SEAL itself. Unfortunately, I cannot also find any related issues in the SEAL github project. It would be better if you can post an issue in the SEAL github.

**Comment by husheng1997** [comment] 2022-10-11 01:47
> > > I'm with similar error (maybe complaining x64 libz.a not compatible),but I haven't solved it yet. ![image](https://user-images.githubusercontent.com/25169930/194192236-9cfd2c9a-ab9c-4bdd-a38e-d82c7cb4297a.png)
> > 
> > 
> > It seems there are some linked libraries related to SEAL. If you1 have any problems installing SEAL based on the source code, we highly recommand using the command "apt-get install seal" to automatically install SEAL and related libraries. Please let me know if "apt-get install seal" works well.
> 
> I followed the guide to install seal on a new computer（Ubuntu18.04） and still get the same error. ![image](https://user-images.githubusercontent.com/25169930/194791700-b8fdc22d-73c8-4645-89c0-981f5f653627.png)
> 
> Then, I tried to install seal again as your suggested command `sudo apt-get install SEAL` or `sudo apt-get install seal`.But it shows that the installation package cannot be found. ![image](https://user-images.githubusercontent.com/25169930/194792154-ffe991a7-3432-422a-ba78-f902fbbb2ebe.png)
> 
> And, I tried to search for the existence of the SEAL installation package, but nothing was found ![image](https://user-images.githubusercontent.com/25169930/194792240-9f9f12d6-57a8-47be-9313-788a7981fa23.png)

We installed Ubuntu 22.04 on the terminal through “Docker pull ubuntu”,and  installed SEAL through the following command：
apt update
apt install cmake
apt install clang
apt install git
git clone https://github.com/microsoft/SEAL
cd SEAL
cmake -S . -B build -D CMAKE_CXX_COMPILER=/usr/bin/clang++ -D CMAKE_C_COMPILER=/usr/bin/clang -DCMAKE_INSTALL_PREFIX=/usr/local
cmake -S . -B build -DCMAKE_CXX_COMPILER=/usr/bin/clang++ -DCMAKE_C_COMPILER=/usr/bin/clang -DCMAKE_INSTALL_PREFIX=/usr/local -DBUILD_SHARED_LIBS=ON -DCMAKE_C_FLAGS_RELEASE="-O3" -DCMAKE_CXX_FLAGS_RELEASE="-O3 -march=native"
cmake --build build
cmake --install build
You can try and install SEAL through these commands.

**Comment by shazi4399** [comment] 2022-10-11 02:04
> 



> > > > I'm with similar error (maybe complaining x64 libz.a not compatible),but I haven't solved it yet. ![image](https://user-images.githubusercontent.com/25169930/194192236-9cfd2c9a-ab9c-4bdd-a38e-d82c7cb4297a.png)
> > > 
> > > 
> > > It seems there are some linked libraries related to SEAL. If you1 have any problems installing SEAL based on the source code, we highly recommand using the command "apt-get install seal" to automatically install SEAL and related libraries. Please let me know if "apt-get install seal" works well.
> > 
> > 
> > I followed the guide to install seal on a new computer（Ubuntu18.04） and still get the same error. ![image](https://user-images.githubusercontent.com/25169930/194791700-b8fdc22d-73c8-4645-89c0-981f5f653627.png)
> > Then, I tried to install seal again as your suggested command `sudo apt-get install SEAL` or `sudo apt-get install seal`.But it shows that the installation package cannot be found. ![image](https://user-images.githubusercontent.com/25169930/194792154-ffe991a7-3432-422a-ba78-f902fbbb2ebe.png)
> > And, I tried to search for the existence of the SEAL installation package, but nothing was found ![image](https://user-images.githubusercontent.com/25169930/194792240-9f9f12d6-57a8-47be-9313-788a7981fa23.png)
> 
> We installed Ubuntu 22.04 on the terminal through “Docker pull ubuntu”,and installed SEAL through the following command： apt update apt install cmake apt install clang apt install git git clone https://github.com/microsoft/SEAL cd SEAL cmake -S . -B build -D CMAKE_CXX_COMPILER=/usr/bin/clang++ -D CMAKE_C_COMPILER=/usr/bin/clang -DCMAKE_INSTALL_PREFIX=/usr/local cmake -S . -B build -DCMAKE_CXX_COMPILER=/usr/bin/clang++ -DCMAKE_C_COMPILER=/usr/bin/clang -DCMAKE_INSTALL_PREFIX=/usr/local -DBUILD_SHARED_LIBS=ON -DCMAKE_C_FLAGS_RELEASE="-O3" -DCMAKE_CXX_FLAGS_RELEASE="-O3 -march=native" cmake --build build cmake --install build You can try and install SEAL through these commands.

Thank you！ SEAL is successfully installed according to the method you provided.

**Comment by liuweiran900217** [comment] 2022-10-12 04:37
We checked our guidelines for installing SEAL and found that there are some errors. We reopen the issue now. After we update mpc4j for 1.0.5, you can see the updated documentation on how to install native libraries (including on the Docker image).

**Comment by liuweiran900217** [comment] 2022-11-14 10:20
Version 1.0.5 has been released. We updated README.md to show how to run mpc4j in Docker. The tests are passed on both MacBook (under x64_84 and M1) and Desktops (under x86_64). Close the issue.

**Closed by liuweiran900217** 2022-11-14 10:20 UTC
